#!/bin/bash

export DEBIAN_FRONTEND=noninteractive 
apt-get update
apt-get dist-upgrade -y
apt-get install -y git-core etckeeper
apt-get install -y ack-grep bash-completion build-essential cu curl htop libssl-dev man-db openssh-server pv python-software-properties telnet tmux tsocks unp unzip vim wget
